### ISSUE TITLE
Diapositiva de las diferencias entre proyecto de mañana y de tarde

### ISSUE THREAD

**Issue by Pablo17p** [ISPPNightTurn/Clubby#13]
Dedicar una diapositiva en la ppt a las diferencias entre nuestro proyecto y el de mañana que se le asemeja según el acuerdo establecido entre ambos Project Managers

**Comment by CavernaryBeast** [comment]
Mediante la refinación de los casos de uso core y la elicitación de requisitos veremos las diferencias claras entre el proyecto de mañana y el de tarde
