### ISSUE TITLE
Documento de requisitos

### ISSUE THREAD

**Issue by migberbay** [ISPPNightTurn/Clubby#15]
Redacción del documento de requisitos.

**Comment by CavernaryBeast** [comment]
@jvrgarciafernandez Echale un vistazo a la presentación y a la documentación y encontrarás todo lo necesario para hacerlo. 

Recuerda hacerlo como nos han enseñado en IISSI y en demás asignaturas del estilo, usando el formato adecuado. Debes recordar los distintos tipos de requisitos: de información, funcionales, no funcionales y reglas de negocio.

Adjunto ejemplo:
![imagen](https://user-images.githubusercontent.com/47127494/75119509-c2600a80-5683-11ea-9115-e8699e1efd50.png)

Recuerda también hacer la matriz de trazabilidad.
