### ISSUE TITLE
Medir las Mejoras

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#163]
- Poner medidas para las mejoras y cuanto de buena es
- Decir el objetivo que se pretende obtener con las mejoras (porcentaje de mejora)
-  En las mejoras se debe incluir los valores absolutos, no solo relativos

Ejemplo: 
![Captura de pantalla (170)](https://user-images.githubusercontent.com/46228346/77636337-3e37c600-6f54-11ea-9c0c-b182883b5220.png)

Algo asi se dijo que estaba muy bien representado

**Comment by CavernaryBeast** [comment]
@rafgirlie Ya que te encargaste de manejar la Retrospective anterior, te encargo la tarea de la medición y redacción de las mejoras. Si tienes alguna duda, lo hablamos.
