### ISSUE TITLE
Mejoras Medicion del Equipo

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#166]
Incluir mejoras en las métricas de medición del equipo. No es realista que mucha gente tenga 10 puntos, hay que buscar mas metricas diferentes

**Comment by CavernaryBeast** [comment]
@Minuke Ya que tú hiciste el diagrama, puedes encargarte de realizar la medición de los miembros del equipo de trabajo completo.
Para facilitar tu tarea, vamos a establecer fechas de finalización anteriores al deadline, a la entrega, y así disponemos de tiempo para hacer todo este tipo de cosas.
