### ISSUE TITLE
Incluir Tests

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#168]
No solo hay que incluir test funcionales, tambien unitarios, de vista, etc.

**Comment by CavernaryBeast** [comment]
Según tengo entendido, @YassinETSII y @joscarboz se encargaron de hacer la mayor parte de los tests. Quizás me olvido de @migberbay , no lo recuerdo bien. El tema, dejad claro en esta Issue que clase de tests habéis realizado e incluid aquellos que nos falten. No tenéis que hacerlos vosotros solos. Podéis crear tareas como en Front-End y asignarlas a los demás miembros de vuestro equipo de trabajo.
