### ISSUE TITLE
Mejorar Interfaz Aplicacion

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#169]
Mejorar interfaz, son colores muy locos

**Comment by CavernaryBeast** [comment]
Asignada al responsable de Front, al de Back y a nuestro responsable de Relaciones Públicas. Creo que sois los más indicados para darle una bonita apariencia a la página. 
La tarea consiste en echarle un vistazo a la página y ver que cosas podrían cambiarse. Cuando tengáis la lista con cosas a cambiar, @ghostedMonster podría crear una serie de issues y asignarselas a los miembros del equipo de Front.
