### ISSUE TITLE
Gestion del Codigo

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#173]
Introducir una gestión de código (política de tags para los entregables)

**Comment by CavernaryBeast** [comment]
Basta con definir un apartado en el documento Sprint 2 donde se encuentre nuestra política de tags y releases. 
Es decir, un apartado donde digamos que, cuando el software esté acabado sacaremos una etiqueta que identificará dicho producto terminado y se publicará en Git como release.
Si le echáis un vistazo a Git, no se si lo sabéis, tiene un apartado para sacar releases y asignarles tags. Podéis comentar que el despliegue será sobre el producto indicado en esa tag para que si alguien quiere probar el producto en local, no tenga que bajarse el repo si no la release correspondiente.

**Comment by CavernaryBeast** [comment]
Como la configuración del proyecto en local y desplegado es distinta, cuando este este terminado hablad conmigo, con @joscarboz o con @migberbay para tratar este tema. El producto a desplegar será aquel que esté en la rama Deploy. El producto para release y que funcionará en local será el que esté en master ya que tendrá la configuración correspindiente a un entorno local.
