### ISSUE TITLE
Arreglar Bugs, Code Smells, code duplicate, etc 

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#176]
Arreglar los errores que aparecen en sonarcloud lo máximo que se pueda. La métrica final debe de dar "passed"

**Comment by CavernaryBeast** [comment]
Coordinaos y delegad en vuestros equipos para resolver los bugs, malos olores y demás conflictos detectados por Sonarcloud. Si los conflictos son externos al proyecto, indicarlo para que lo pongamos en la presentación.
