### ISSUE TITLE
Back-End: ERRORES

### ISSUE THREAD

**Issue by joscarboz** [ISPPNightTurn/Clubby#207]
Error al editar el corre de un usuario.
Error al eliminar un club

**Comment by joscarboz** [comment]
Puedes editar un club introduciendo un NIF no válido

**Comment by migberbay** [comment]
error al eleiminar un club (fixed)

**Comment by migberbay** [comment]
error al editar perfil con emails(fixed)
error al editar club validation (fixed)

**Comment by joscarboz** [comment]
Error con placeholder al buscar evento (fixed)
Error eventos pasados apareciendo en busqueda(fixed)

**Comment by joscarboz** [comment]
Error al intentar editar un perfil y dejar el mismo email
Cuando haces payout sin dinero, el /payout se queda pegado en la url y da panic al editar perfil
Si en Maps no se encuentra la dirección, da panic
Problemas al meter ñ en username o password (Deberiamos controlarlo y poner en la descripcion del campo los caracteres que traga)
Avisar de que necesitas meter al menos una letra en la contraseña

**Comment by AlfonsoRodriguezRomero** [comment]
Necesario evitar que en el campo de fechas se pueda escribir algo distinto a una fecha en caso de que no se use el datepicker (por ejemplo, tabulando hasta el campo).
En edit_profile.html hay un método comentado que muestra el datepicker con un botón, pero no mete el valor elegido en el campo de birth_date.

**Comment by joscarboz** [comment]
Se pueden crear eventos para el mismo dia en horas pasadas, y estos eventos ya terminados se siguen listando durante ese dia.

**Comment by migberbay** [comment]
Error al intentar editar un perfil y dejar el mismo email(fixed)
Cuando haces payout sin dinero, el /payout se queda pegado en la url y da panic al editar perfil (FIXED)
Si en Maps no se encuentra la dirección, da panic(fixed)

**Comment by migberbay** [comment]
Necesario evitar que en el campo de fechas se pueda escribir algo distinto a una fecha en caso de que no se use el datepicker (por ejemplo, tabulando hasta el campo).(fixed)

**Comment by migberbay** [comment]
Se pueden crear eventos para el mismo dia en horas pasadas, y estos eventos ya terminados se siguen listando durante ese dia.(fixed)

**Comment by joscarboz** [comment]
No se pueden crear clubs pero si editar (Parece que la query solo recibe datos de Maps)
