### ISSUE TITLE
Introducción de cadenas en los campos de fecha devuelve panic

### ISSUE THREAD

**Issue by YassinETSII** [ISPPNightTurn/Clubby#229]
En aquellos formularios contenedores de un campo fecha, se puede introducir una cadena de texto, carácter, etc... y hace que el sistema pete con un panic. Se pueden introducir si se tabula entre campo y campo hasta llegar al de la fecha y con un control + v se pega el texto. También se puede introducir mediante el inspeccionar. 

![image](https://user-images.githubusercontent.com/44404557/79561816-3fb76280-80aa-11ea-9a34-6637843836b9.png)

**Comment by migberbay** [comment]
esto es para frontend no debemos dejar editar esos campos a mano, se deben editar exclusivamente con el datepicker.

**Comment by migberbay** [comment]
esto se ha solucionado.
