### ISSUE TITLE
Generación de códigos QR

### ISSUE THREAD

**Issue by CavernaryBeast** [ISPPNightTurn/Clubby#232]
Debéis dar una solución al problema del error 500 con la generación de código QR y documentarla.

@joscarboz Cuando se solucione el tema hablas conmigo (@CavernaryBeast ) y documento la solución implementada.

Se incluirá dicha documentación en el documento Sprint 3

**Comment by migberbay** [comment]
esto si no me equivoco es lo que ya hemos hecho de dejar solo botones al display no?

**Comment by CavernaryBeast** [comment]
Asunto cerrado. Podéis ver la solución implementada en el repositorio del equipo, en el documento pertinente:.
