### ISSUE TITLE
Compra de Tickets

### ISSUE THREAD

**Issue by CavernaryBeast** [ISPPNightTurn/Clubby#237]
No se confirma la compra de tickets con ningún mensaje, volviendo a la página descriptiva del ticket. 

Además estaría bien que nos indique cuántos tickets hemos comprado de un tipo en el propio listado.

**Comment by joscarboz** [comment]
Hacer que si tienes dinero y se compra te redirija a la pagina de Thank for believing in us, pero que si  no tienes dinero haga lo que hacia, marcando el mensaje de error.
