### ISSUE TITLE
Dirección no válida en crear o actualizar club

### ISSUE THREAD

**Issue by YassinETSII** [ISPPNightTurn/Clubby#242]
Cuando se introduce una cadena como 11111111111111111111111111 o aaaaaaaaaaaaaaaaaaaaaaa en el campo de dirección, tanto creando como actualizando un club, devuelve un error. El error que devuelve es el de list index out of range.
![image](https://user-images.githubusercontent.com/44404557/79587559-01826900-80d3-11ea-83a7-3b5cb3e14e19.png)

**Comment by migberbay** [comment]
fixed
