### ISSUE TITLE
Campaña de Marketing: Anuncios

### ISSUE THREAD

**Issue by CavernaryBeast** [ISPPNightTurn/Clubby#262]
Dedico esta Issue a la investigación de los siguientes puntos relacionados con el advertising de nuestro producto Clubby. Resumidamente debemos investigar sobre las alternativas de las que disponemos para anunciarnos y llegar a nuestro nicho de mercado

- Medios para anunciarnos: Investigar los medios disponibles, sus costes y todo lo que sea de ayuda para llegar más facilmente a nuestro target.

Ejemplo: Investigar sobre lo que costaría anunciarse en la tele, dependiendo de la duración del anuncio y de la hora seleccionada para anunciarnos. Investigar sobre otras alternativas como anunciarnos en las paradas de bus, carteles grandes, centros comerciales, dedicar tiempo y dinero a la publicidad por la calle, etc.

**Comment by CavernaryBeast** [comment]
Os asigno a vosotros concretamente porque:

- A @rafgirlie se le da bien la gestión de costes

- @ManuelRecio conoce el mercado y nuestro público objetivo, por lo que podría pensar en formas de anunciarnos ingeniosas, como contratar a RRPP o cosas así

- @Minuke También puede aportar ideas ingeniosas y su forma de redactar creo que es la apropiada para tareas que necesiten bastante texto

**Comment by Minuke** [comment]
Voy a empezar por el marketing para las cadenas de TV,

**Comment by Minuke** [comment]
Informe del marketing sobre la TV finalizado. Se puede ver en el siguiente enlace:

https://drive.google.com/drive/folders/1oiU-7nNJFlu6MCZEbJbGajDpqqv2DpJK
