### ISSUE TITLE
Arreglar documentos para el aprobado

### ISSUE THREAD

**Issue by joscarboz** [ISPPNightTurn/Clubby#276]
En el protocolo de puesta en producción no se indican los responsables de las pruebas y del despliegue, ni el procedimiento para escogerlos. Tampoco se indica cómo se van a realizar las pruebas. Todas las frases con verbos impersonales (se testea, se comprueba, ...) deben cambiarse indicando la persona o rol encargado y/o responsable de las tareas.

**Comment by CavernaryBeast** [comment]
Hecho. En el documento Protocolo de Puesta en Producción pueden verse los cambios realizados.
