### ISSUE TITLE
Back-End: Cambiar sistema de añadir fotos

### ISSUE THREAD

**Issue by joscarboz** [ISPPNightTurn/Clubby#279]
Intentar cambiar el método de añadir fotos de eventos, clubes y perfiles. Cambiado el uso de URLs por poder subirlas

**Comment by CavernaryBeast** [comment]
Es inviable. La realización de esta tarea se ha cancelado. Podemos encontrar detalles en el documento Aclaraciones sobre las caracteristicas de Clubby
