### ISSUE TITLE
Realizar un DAFO de la aplicación

### ISSUE THREAD

**Issue by Pablo17p** [ISPPNightTurn/Clubby#28]
Llevar a cabo un DAFO (Debilidades, Amenazas, Fortalezas y Oportunidades) de nuestro proyecto, documentarlo e incluir un cuadro-resumen en la presentación

**Comment by CavernaryBeast** [comment]
Hecha. Pendiente de que @JaviToro le eche un vistazo y de el visto bueno del apartado de diseño de la matriz.
