### ISSUE TITLE
Definicion de modelos (objectos a persistir) y UML asi como documeto de requisitos

### ISSUE THREAD

**Issue by migberbay** [ISPPNightTurn/Clubby#53]
- Redactar los modelos que necesitamos y las variables que deben almacenar cada una de ellas.

- Crear el UML de los modelos relacionales y las relaciones de cada uno de ellos (DP style)

- Determinar si usaremos astah comunity u otro creador de modelos si es asi cual.

- Redactar el documento de requisitos funcionales, no funcionales etc.

**Comment by joscarboz** [comment]
UML: Jose Caro

**Comment by Minuke** [comment]
Definición de los objetos a persistir: Jose Manuel Minuesa

**Comment by joscarboz** [comment]
Para UMLs usaremos drawio al ser sencillo, rápido y totalmente gratuito
