### ISSUE TITLE
Modelos, Vistas y Templates...

### ISSUE THREAD

**Issue by migberbay** [ISPPNightTurn/Clubby#54]
una vez terminadas las tareas de la issue #53 
se debe:
- añadir los modelos del UML a los models.py
- añadir las clases necesarias para cumplir con los requisitos funcionales.
- investigar la inclusion de las APIS necesarias.
- definir templates basicas para los de frontend.
- investigacion sobre el despliegue en google cloud y documentar los cambios necesarios para pasar de local a despligue.

**Comment by joscarboz** [comment]
models.py añadidos

**Comment by joscarboz** [comment]
Ya se pueden listar y crear productos desde una cuenta de club

**Comment by joscarboz** [comment]
Club owners now can create products and assign them to any of the clubs they own. They can also create events and list only the ones taking place in clubs they own. Same thing with products.
