### ISSUE TITLE
Generación de entradas al crearse un evento

### ISSUE THREAD

**Issue by YassinETSII** [ISPPNightTurn/Clubby#78]
Una vez creado un evento se deberán crear las entradas especificando la cantidad que se ponen a la venta y su precio. Añadir un contador del número de entradas para cada evento, donde se decremente con cada compra.

**Comment by migberbay** [comment]
esto no es exactamente asi, tal y como estamos planteandolo el evento se crea solo y luego a posteriori creas entradas de diferentes precios

**Comment by migberbay** [comment]
yo me quiero encargar de este tema si puede ser que es justo con lo que estaba antes

**Comment by joscarboz** [comment]
por mi perfecto. he hecho las asignaciones tarde y malamente, asi que
cambiate a donde veas

**Comment by SiiNerGia** [comment]
Se me habia olvidado asignarme esto que lo estuve hablando con miguel, me lo asigno

**Comment by jvrgarciafernandez** [comment]
Falta coger y cambiar el campo max del formulario para que el número de maximo de entradas sea el aforo
