### ISSUE TITLE
Redes sociales para Clubby

### ISSUE THREAD

**Issue by Minuke** [ISPPNightTurn/Clubby#92]
Crear redes sociales de la aplicación. En un principio se tienen pensado twitter (aunque hay un usuario con este nombre ya) e instagram

**Comment by CavernaryBeast** [comment]
Crear videos o storyboard para vender tu aplicación a usuarios y clientes (para más adelante). Tener un videos especifico para el cliente y otro para el usuario.

**Comment by Minuke** [comment]
Credenciales de instagram:
 - nombre de usuario: ClubbyParty
 - Conraseña: clubbyispp

**Comment by Minuke** [comment]
Instagram: clubbyparty
Password: clubbyispp
